language: rust
before_script:
  - (cargo install mdbook --force || true)
script:
  - mdbook build
  - mdbook test
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
